* Style guidelines:

  I intend to use this document to leave daily notes and conversations so we have them available to refer to.

Outermost items should merely be a date. Because I started the document and because this is on Portuguese date system for historical reasons, the dates will be in Portuguese, so
 <year-month-day> day-of-week

Underneath the outermost item should be note topics. 

In each note topic, I think we should trade off with headers simply named 
"David" for David I. Spivak and 
"Jaz" for David Jaz Myers. 

(Jaz: Feel free to choose your own name David)

* <2020-07-13 seg> 

** Conventions for labelling:
   How should we label our equations, theorems, lemmas, propositions, etc
   


*** Jaz: 
    My usual convention is 
      kind:name.of.particular.item

    e.g. 
      thm:polynomial.functors.are.dope

    or 
      eqn:really.complicated.diagram1 
 
      (though, hopefully with better names)

    I suppose it might be useful to also label according to their chapter, like

    C1:eqn:just.a.single.box

    Any ideas?

*** Spiv: 
My usual convention is 
      kind.name_of_particular_item

Diagram that's random
      eqn.polynomial_misc958


** Drawing a mapsto nicely:
   (This is a real question, but also a nice way to demonstrate how org-mode hyperlinks work :) ) 

*** Jaz:
    I'm having trouble drawing this mapsto nicely: [[file:~/Documents/Books/DynamicalSystemsBook/book/C1-.tex::#problem-drawing-mapsto-nicely][See situation here.]] 
    
    I want this to look nice, as in, to have the mapsto line up under the to, but I've never really known how to get that effect.
** Naming conventions for discrete-time dynamical systems
   We have a number of discrete-time dynamical systems (in various doctrines). 

   We discussed it, and we came up with this convention:
     adjective system

   For example:
     deterministic system
   For a deterministic automaton aka Moore machine

     stochastic system
   For a stochastic automaton aka Markov decision process

     dependent system
   For a Poly-dynamical system. 
   
   This also lets us use the word "system" for short.

* <2020-07-14 ter>  

** Polynomials: are the coefficients sets or natural numbers?
   

*** Jaz:
    Since the coefficients are sets, they should be drawn differently from natural numbers.

    My suggestion is a bold-face


*** Spiv:
    I want to use natural numbers, as usually type-set, for my coefficients.

    So we will be instead denoting natural numbers by a different font-face. 

