* Style guidelines:

  I intend to use this document to leave daily notes and conversations so we have them available to refer to.

Outermost items should merely be a date. Because I started the document and because this is on Portuguese date system for historical reasons, the dates will be in Portuguese, so
 <year-month-day> day-of-week

Underneath the outermost item should be note topics. 

In each note topic, I think we should trade off with headers simply named 
"David" for David I. Spivak and 
"Jaz" for David Jaz Myers. 

(Jaz: Feel free to choose your own name David)

* Dailies
** <2020-07-13 seg> 
  
*** DONE Conventions for labelling:
    CLOSED: [2020-07-15 qua 23:40]
    How should we label our equations, theorems, lemmas, propositions, etc
   


**** Jaz: 
     My usual convention is 
       kind:name.of.particular.item

     e.g. 
       thm:polynomial.functors.are.dope

     or 
       eqn:really.complicated.diagram1 
 
       (though, hopefully with better names)

     I suppose it might be useful to also label according to their chapter, like

     C1:eqn:just.a.single.box

     Any ideas?

**** Spiv: 
 My usual convention is 
       kind.name_of_particular_item

 Diagram that's random
       eqn.polynomial_misc958


*** DONE Drawing a mapsto nicely:
    CLOSED: [2020-07-15 qua 23:40]
    (This is a real question, but also a nice way to demonstrate how org-mode hyperlinks work :) ) 

**** Jaz:
     I'm having trouble drawing this mapsto nicely: [[file:~/Documents/Books/DynamicalSystemsBook/book/C1-.tex::#problem-drawing-mapsto-nicely][See situation here.]] 
    
     I want this to look nice, as in, to have the mapsto line up under the to, but I've never really known how to get that effect.

   
**** Jaz: RESOLVED
     I believe it looks fine how I am doing it now <2020-07-15 qua> 

*** DONE Naming conventions for discrete-time dynamical systems
    CLOSED: [2020-07-15 qua 23:40]
    We have a number of discrete-time dynamical systems (in various doctrines). 

    We discussed it, and we came up with this convention:
      adjective system

    For example:
      deterministic system
    For a deterministic automaton aka Moore machine

      stochastic system
    For a stochastic automaton aka Markov decision process

      dependent system
    For a Poly-dynamical system. 
   
    This also lets us use the word "system" for short.

** <2020-07-14 ter>  

*** DONE Polynomials: are the coefficients sets or natural numbers?
    CLOSED: [2020-07-15 qua 23:40]
   

**** Jaz:
     Since the coefficients are sets, they should be drawn differently from natural numbers.

     My suggestion is a bold-face


**** Spiv:
     I want to use natural numbers, as usually type-set, for my coefficients.

     So we will be instead denoting natural numbers by a different font-face.

**** Resolution:
     We will use mathsf for ordinals. 

     This has been added to the preamble.

** <2020-07-15 qua> 

  

*** DONE Jaz: Turing Machine Example
    CLOSED: [2020-07-15 qua 23:29]

*** DONE Jaz: Clean up equations
    CLOSED: [2020-07-16 qui 00:01]
    You need to copy in     , baseline=(Y.center) 
    into all the diagrams
   
    Also some of them say things like box1 in the tag, or just don't look good

   
*** DONE Jaz: Deal with "Anatomy of a lens"
    CLOSED: [2020-07-16 qui 00:02]
    Think I'll just delete it.
* Citations
** C1-
*** Turing Machine in Introduction
   [[file:~/Documents/Books/DynamicalSystemsBook/book/C1-.tex::#cite-this.turing_maching][Find it here.]] 

   
   I found this machine [[http://www.ini.uzh.ch/~tneary/NearyWoods_FI2009.pdf][here]]
   DOI 10.3233/FI-2009-0008
  in section 3.4, named $U_{6, 4}$. The table is adapted from there
  
