name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: DynamicalBook.tex
          working_directory: book
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
          extra_system_packages: py-pygments
      - name: Uploads the document
        uses: actions/upload-artifact@v2
        with:
          name: DynamicalBook
          path: book/DynamicalBook.pdf
      - run: mkdir build
      - run: cp book/DynamicalBook.pdf build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
