name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@latest
        with:
          root_file: DynamicalBook.tex
          working_directory: book
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
          extra_system_packages: python-pygments
      - name: Uploads the document
        uses: actions/upload-artifact@v2
        with:
          name: DynamicalBook
          path: book/DynamicalBook.pdf
      - run: mkdir build
      - run: cp book/DynamicalBook.pdf build/
      - uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: build/
          GH_PAT: ${{ secrets.GH_PAT }}
